### ISSUE TITLE
フロントエンド・バックエンド間のプロトコル

### ISSUE THREAD

**Issue by sei0o** [sei0o/binchotan-backend#2]
現状は、`UnixStream` (UNIX domain socket) 上で情報を[やりとり](https://github.com/sei0o/binchotan-backend/commit/f4e93d200cbb242cd9921eda0b3f8d34e6703e46)している。stream上なので終端（EOF）が存在しないので、とりあえず `\n` を区切り記号に使って、その前後でメッセージを区別している。しかしこれは対症療法であって、今後面倒になりそうなのでやめたい。面倒なことには、たとえば、 `\n` を含むペイロードをエスケープする必要が挙げられる。

cf. [Anyone knows how to write bytes with EOF when using UnixStream : rust](https://www.reddit.com/r/rust/comments/em6rzh/anyone_knows_how_to_write_bytes_with_eof_when/)

**Comment by sei0o** [comment]
別にやめなくてもいいかもな

**Comment by eniehack** [comment]
HTTPみたく`\r\n`で改行してもいいかなと思ったけど、`\n`でもいいかも？
JSONだとbackquoteはescapeされるし

「`r\n`で改行」は、こんな感じを想定してた:
```
[payload]\r\n
\r\n
```

あと、mpdは`\n`で改行してそう
https://mpd.readthedocs.io/en/latest/protocol.html

**Comment by sei0o** [comment]
たしかにエスケープされてるから支障はないんだよなあ
