### ISSUE TITLE
AURのパッケージ化

### ISSUE THREAD

**Issue by eniehack** [sei0o/binchotan-backend#22]
VCSパッケージに関しては、out-of-dateフラグを立てられることもないので、`binchotan-backend-git`みたいな名前でAURに投稿してもよさそう

depends: #21

参考:
- [Arch User Repository#パッケージの共有](https://wiki.archlinux.jp/index.php/Arch_User_Repository#.E3.83.91.E3.83.83.E3.82.B1.E3.83.BC.E3.82.B8.E3.81.AE.E5.85.B1.E6.9C.89)
- [パッケージの作成](https://wiki.archlinux.jp/index.php/%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AE%E4%BD%9C%E6%88%90)
- [Arch パッケージガイドライン](https://wiki.archlinux.jp/index.php/Arch_%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3)
- [Rust パッケージガイドライン](https://wiki.archlinux.jp/index.php/Rust_%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3)

**Comment by sei0o** [comment]
see #24 (closed?)
