### ISSUE TITLE
API Scope

### ISSUE THREAD

**Issue by sei0o** [sei0o/binchotan-backend#6]
OAuthはscope（スコープ; パーミッションと同義）によってリソースへのアクセスを制限している。Twitterを例に挙げると、`user.read, tweet.read, mute.write` などのスコープが定義されている。binchotanはデフォルトでは `user.read, tweet.read, offline.access` のみを使用しているが、これだとfrontend, filterから行える操作が限られてしまう（たとえば、上記の権限では `tweet.write` がないのでツイートすらできない）。

あらかじめbackendに全権を与えるのが簡単だが、なるべく権限を絞るためにはfilter, frontend側から権限をリクエストできる仕組みがほしい。

**Comment by eniehack** [comment]
filterに関しては`binchotan.toml`に`List`で要求する権限を記述するとか……？
related: #4

**Comment by sei0o** [comment]
access tokenのキャッシュに当時の権限も入れておいたほうがいいな

**Comment by sei0o** [comment]
binchotan.tomlに項目を追加して、起動時とフィルタの適用時に権限を照合するようにしました
